#!/bin/bash

os=$(cat /etc/os-release | grep -E '^PRETTY_NAME=' | cut -d'"' -f2 | cut -d'=' -f2)

kr=$(uname -r | cut -d'-' -f1)
pa=$(pacman -Q | wc -l)
rs=$(xrandr | grep '\*' | awk '{print $1}')
sh=${SHELL##*/}

id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
id=${id##* }
wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)
wm=${wm##*WM_NAME = \"}
wm=${wm%%\"*}

s='\e[0;7m';  e='\e[0;m'; d='  ';
r='\e[0;31m'; g='\e[0;32m'; b='\e[0;34m';
c='\e[0;36m'; y='\e[0;33m'; m='\e[0;35m';
f='\e[0;37m';

rb='\e[0;41m'; gb='\e[0;42m'; bb='\e[0;44m';
cb='\e[0;46m'; yb='\e[0;43m'; mb='\e[0;45m';

w='\e[0;38m'; wb='\e[0;48m';

colors="${f}${d}${r}${d}${y}${d}${g}${d}${b}${d}${c}${d}${m}${d}${w}"
printf "
              ${r}wm   ${w}${wm}
   (\\ /)      ${y}kr   ${w}${kr}
   ( . .)     ${g}sh   ${w}${sh}
   c(${r}\"${w})(${r}\"${w})    ${m}rs   ${w}${rs}

"
printf "$colors\n"
