#!/bin/bash

os=$(cat /etc/os-release | grep -E '^PRETTY_NAME=' | cut -d'"' -f2 | cut -d'=' -f2)

kr=$(uname -r | cut -d'-' -f1)
pa=$(pacman -Q | wc -l)
rs=$(xrandr | grep '\*' | awk '{print $1}')
sh=${SHELL##*/}

id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
id=${id##* }
wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)
wm=${wm##*WM_NAME = \"}
wm=${wm%%\"*}

r='\033[0;31m'
g='\033[0;32m'
b='\033[0;34m'
c='\033[0;36m'
y='\033[0;33m'
m='\033[0;35m'
w='\033[0;38m'

printf "
              ${r}wm   ${w}${wm}
   (\\ /)      ${y}kr   ${w}${kr}
   ( . .)     ${g}sh   ${w}${sh}
   c(${r}\"${w})(${r}\"${w})    ${m}rs   ${w}${rs}

"
harmony-show-colors
